version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: voucher-postgres
    restart: always
    ports:
      - "5433:5432" # Bên trong container là 5432, bên ngoài ta dùng 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: natv1211212212
      POSTGRES_DB: voucherdv
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
